### ISSUE TITLE
Persistent Storage

### ISSUE THREAD

**Issue by nhawke** [super-cooper/memebot#13]
**Is your feature request related to a problem? Please describe.**
Several existing feature requests (#3. #4, #6, possibly #7, possibly #11) require persistent storage of some sort. Future feautres may likely also need this. It's probably a good idea to add a framework for this ASAP becasue it is a prerequisite for existing issues. 

**Describe the solution you'd like**
Some abstract framework for accessing persistent storage. I think people have discussed using MongoDB for DB-style persistent storage. I think it be ideal to also support reading simple text files for less-complex needs (e.g. #6 might only require a text or JSON file consisteing of a list of titles depending on how it is implemented)

**Describe alternatives you've considered**
Keeping everything in RAM. Not ideal.

**Additional context**

**Comment by super-cooper** [comment]
https://github.com/super-cooper/memebot/pull/14#discussion_r334282771
