### ISSUE TITLE
Tidy documentation

### ISSUE THREAD

**Issue by super-cooper** [super-cooper/memebot#20]
**Does this improvement fix a bug/issue? Please describe.**
Some of our code is undocumented

**What do you dislike about the feature in its current state?**
Lack of documentation

**Describe the solution you'd like**
Add docstrings to functions/classes that don't have them, and comments to confusing code

**What tradeoffs are made by implementing your improvement?**
Lots of things will be getting refactored early, and we may waste time documenting code that gets deleted

**Describe alternatives you've considered**
Do nothing lol

**Additional context**
N/A

**Comment by nhawke** [comment]
things to do for this include 
* how to run the bot
    * the docker commands (if you wanna test with docker)
    * venv commands 
* update docs on available flags
* installing requirements
* where / how to get api keys
