### ISSUE TITLE
Better / More standardized help command

### ISSUE THREAD

**Issue by nhawke** [super-cooper/memebot#27]
**What do you dislike about the feature in its current state?**
The `!help` command doesn't accept arguments, so it is difficult or impossible to get hepl for a specific command.

**Describe the solution you'd like**
1. All commands should have command-specific help messages
2. Help accepts an optional command argument. If that argument matches an existing command, the command-specific help is shown.
3. For standardization, any commands which require specific arguments should print their command-specific help message when when they are invoked with improper arguments. 

**What tradeoffs are made by implementing your improvement?**
More work in exchange for better UX 

**Describe alternatives you've considered**
* rewriting the bot in Go with this feature included

**Comment by super-cooper** [comment]
this will be easier to do when #19 is done

**Comment by super-cooper** [comment]
Would we agree that this has been completed by #39 and #52?

**Comment by super-cooper** [comment]
> Would we agree that this has been completed by #39 and #52?

I take it back; we should modify `!help` to take command names as arguments.

**Comment by super-cooper** [comment]
Fixed by #89
