### ISSUE TITLE
Include user's name in !hello output

### ISSUE THREAD

**Issue by nhawke** [super-cooper/memebot#28]
**What do you dislike about the feature in its current state?**
!hello is too generic. I want the bot to say hello *to me*.

**Describe the solution you'd like**
Output is instead "Hello, [user]!" where [user] is the nickname of the user who called the command. If the user has no nickname, use their username.

**What tradeoffs are made by implementing your improvement?**
the hello command needs to actually have logic, but it makes the command more fun.

**Describe alternatives you've considered**
leaving hello as is

**Comment by super-cooper** [comment]
Revisiting this. How do we feel about it?

**Comment by RobertWLeslie** [comment]
is there a valid reason to keep `!hello `as a command aside from historical reasons?

**Comment by super-cooper** [comment]
> is there a valid reason to keep `!hello `as a command aside from historical reasons?

It's the easiest way to ping the bot
