### ISSUE TITLE
Add automated testing infrastructure

### ISSUE THREAD

**Issue by super-cooper** [super-cooper/memebot#31]
**Is your feature request related to a problem? Please describe.**
We keep running into simple bugs because we have no unit tests or anything of the sort. We should have a series of tests that are required to pass before a change is merged.

**Describe the solution you'd like**
For now, something simple like the python [unittest](https://docs.python.org/3/library/unittest.html) framework should suffice. If our needs become more complex, we can use something more robust later.

There is also a library specifically made for testing Discord bots that @nhawke has mentioned to me before. We should absolutely incorporate this into our unit tests.

**Describe alternatives you've considered**
The only other Python unit testing framework I know of is PyTest, but I've never used that before. 

**Additional context**
We should probably use continuous integration to prevent things from being merged without testing. This should be a separate, future ticket that depends on this one.

**Comment by nhawke** [comment]
Using the discord bot testing library probably isn't necessary. This will be easier with #19 done.

**Comment by super-cooper** [comment]
We should do it anyway so we can see what output looks like

**Comment by super-cooper** [comment]
https://github.com/JakeCover/distest

**Comment by super-cooper** [comment]
http://mypy-lang.org/

**Comment by super-cooper** [comment]
Re-assigning this to myself since it's blocking a bunch of stuff and I feel like working on the bot
