### ISSUE TITLE
Events command

### ISSUE THREAD

**Issue by super-cooper** [super-cooper/memebot#4]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
A basic `!event` command that allows us to create events, similar to Facebook messenger. Users should be able to create an event using `!event create` with a name and description, and configure reminders to happen leading up to the event. The bot should create a group for the event (so users involved can be tagged at once), and then delete it 1 day after the event happens. Users should be able to list events by typing `!event list`, and the bot will output each event, the description of the event, and the time at which it is happening. Users can rsvp for an event by using `!event <name> going` or `!event <name> nogo`. If a user is going to an event, they will be added to the event group. Optional `...` arguments at the end of the event creation command should be groups or users that are being invited (i.e. `@home`). If no arguments are provided, default is `@everyone`.

**Describe alternatives you've considered**
Something more intuitive than "nogo" for RSVP might be an option, but I couldn't think of anything else that is one word long.

**Additional context**
N/A

**Comment by RobertWLeslie** [comment]
Would a library of commands be better to handle rather than a bunch of keywords after the command name? such as...
```
!createEvent <event name> <event date>

!eventList

```

**Comment by super-cooper** [comment]
> Would a library of commands be better to handle rather than a bunch of keywords after the command name? such as...

My thoughts were using the same command makes it easier to remember because every command "name" has to be in the same format. And the whole command can also be lowercase and still look good. I want to hear what others think though because this is just what I think would be the easiest for _me_.

**Comment by nhawke** [comment]
> > Would a library of commands be better to handle rather than a bunch of keywords after the command name? such as...


> My thoughts were using the same command makes it easier to remember because every command "name" has to be in the same format. And the whole command can also be lowercase and still look good.

Agree with Adam. Also, having it be just one command is the standard for commands (both command line and commands in a chat setting)

**Comment by super-cooper** [comment]
It seems Discord is adding events as an official supported feature, so this issue will probably end up closed when that lands for our server. However, we do still need the cron-like functionality this feature would provide, so we could either change the metadata of this issue or create a new one for that. I am personally leaning towards creating a new one.

**Comment by super-cooper** [comment]
Since Discord events are now live, and we are able to give permission to everyone to create events, this ticket is now closed. Thank you @discord for doing our jobs.
