### ISSUE TITLE
Add an emote if a linked tweet has been deleted

### ISSUE THREAD

**Issue by pfrissora** [super-cooper/memebot#42]
**Is your feature request related to a problem? Please describe.**
Yeah there's a problem when I go to click on a tweet thats been sent and it's been deleted, wasting valuable seconds of my life. 

**Describe the solution you'd like**
Have the bot put the red X emoji as an emote if the tweet has been deleted. 

**Describe alternatives you've considered**
a trash can would work too. 

**Additional context**

**Comment by super-cooper** [comment]
Impractical. We'd need a background process to request every twitter link that has ever been posted on the server periodically.
