### ISSUE TITLE
React to twitter threads with 🧵

### ISSUE THREAD

**Issue by super-cooper** [super-cooper/memebot#67]
**Is your feature request related to a problem? Please describe.**
Users currently have to alert the channel that a tweet they've posted is actually a thread by either writing it out or reacting with a 🧵 emoji

**Describe the solution you'd like**
Memebot should detect when a tweet has multiple replies from the user who posted it and react with a 🧵

**Describe alternatives you've considered**
This might be confusing for tweets that have people promoting stuff underneath them. We could consider something a thread only if it passes a certain threshold of replies by the OP, but that would also leave out things like people replying to their own tweet with another joke.

**Additional context**
Should be pretty similar to the work done for image number reactions in #40

**Comment by nhawke** [comment]
Seems to me that this is very difficult or impossible without using the Twitter API v2. We currently use v1.1 through Tweepy, but Tweepy does support v2. So if we ever want to do this, we'll have to migrate (which might not be too bad considering the limited scope of our usage).

**Comment by super-cooper** [comment]
Would upgrading Tweepy be small enough to fit into this task or should I make a separate issue?

**Comment by super-cooper** [comment]
Update:

While investigating whether or not this feature is possible in v2, @nhawke discovered that, while v2 has the facilities for us to implement this feature, there is no support for videos in media links. This initially made this feature _and_ a v2 upgrade seem impossible, but we realized we could simply use both APIs wherever they are needed. 

It is unknown whether or not Twitter has plans to deprecate/remove API v1.1, this solution will work for the foreseeable future. 

I will create another issue for integrating a v2 API handle so that we can do work on this issue.
