### ISSUE TITLE
Trigger words for reaccs 

### ISSUE THREAD

**Issue by pfrissora** [super-cooper/memebot#9]
**Does this improvement fix a bug/issue? Please describe.**
A clear and concise description of what the the issue is. Ex. This feature doesn't work under these conditions [...]

**What do you dislike about the feature in its current state?**
A clear and concise description of what you don't like about the feature in its current state, and why your suggestion is a necessary improvement.

**Describe the solution you'd like**

**What tradeoffs are made by implementing your improvement?**
A clear and concise description of what (if anything) would be given up or lost if we changed the feature to your specification.

**Describe alternatives you've considered**

**Additional context**

**Comment by super-cooper** [comment]
Please resubmit issue correctly
