### ISSUE TITLE
Have the memebot send a link every day at 11:59 pm to sportsball

### ISSUE THREAD

**Issue by pfrissora** [super-cooper/memebot#98]
https://didshoheihomertoday.com/

Sent everyday at 11:59 to Sportsball, so i know if my sweet boi has demolished a ball yet today

**Comment by super-cooper** [comment]
would depend on #45 for cron-like infrastructure

**Comment by super-cooper** [comment]
This doesn't seem particularly useful, and perhaps spammy. @pfrissora if you ever want to open a PR, feel free ;)
